version: '3'

services:
  app:
    build: ./app
    ports:
      - '3000:3000'
    networks:
      - network
    volumes:
      - ./app/index.js:/app/index.js
    depends_on:
      - mysql

  nginx:
    image: nginx:1.23.1-alpine
    ports:
      - '8080:80'
    networks:
      - network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - network
    environment:
      - MYSQL_DATABASE=local
      - MYSQL_ROOT_PASSWORD=root

networks:
  network:
    driver: bridge
